### ISSUE TITLE
Formatting *.html files

### ISSUE THREAD

**Issue by igimanaloto** [panoply/vscode-shopify-liquid#5]
Hi! Thanks so much for this... have been wanting autoformatting for liquid files for the longest time!

Can you kindly support non-standard liquid extensions? E.g. applying liquid formatting to *.html files.

Thank you!

**Comment by panoply** [comment]
Hey @igimanaloto 

have you tried associating the extension? eg:

```json
"files.associations": {
    "*.html": "liquid"
  },
```

**Comment by panoply** [comment]
Hey @igimanaloto the extension now supports `*.html` file formatting by default. If your  `.html` files does not contain any liquid code it will still format so I would advise when you don't have liquid HTML to disable the formatting (`cmd+shift+p` and search for liquid).

Also, support for Jekyll frontmatter YAML was added.
